SELECT DISTINCT ?prop ?label ?desc ?type WHERE {
  ?prop wdt:P31/wdt:P279* wd:CLASS_ID .
  ?prop wikibase:propertyType ?type .
  OPTIONAL { ?prop rdfs:label ?label .
             FILTER ( LANG(?label) = "LANG_CODE" ) . }
  OPTIONAL { ?prop schema:description ?desc .
             FILTER ( LANG(?desc) = "LANG_CODE" ) . }
}
