SELECT ?prop ?name ?parent ?depth
WHERE
{
  SERVICE gas:service {
    gas:program gas:gasClass "com.bigdata.rdf.graph.analytics.SSSP" ;
                gas:in wd:Q18616576 ;
                gas:traversalDirection "Reverse" ;
                gas:out ?prop ;
                gas:out1 ?depth ;
                gas:maxIterations 10 ;
                gas:linkType wdt:P279 .
  }
  ?prop wdt:P279 ?parent .
  OPTIONAL { ?prop rdfs:label ?name .
             FILTER( LANG(?name) = "en" ) . }
}
ORDER BY ?depth
